if grados == 0 : print("nulo")
elift 0 < grados < 90 : print("agudo")
elif grados == 90 : print("recto")
elif 90 < grados < 180 : print("obtuso")
elif grados == 180 : print("llano")
elif 180 < grados < 360 : print("completo")
else : print("KeyError")